import { Card, CardHeader, CardTitle, CardDescription } from "@/components/ui/card"
import { Shield, MessageSquare, Users, Network, GitFork, Code } from 'lucide-react'

export function FeaturesGrid() {
  const features = [
    {
      icon: Shield,
      title: "Action Validation",
      description: "Validate and restrict AI agent actions using customizable rules and policies."
    },
    {
      icon: MessageSquare,
      title: "Content Filtering",
      description: "Filter and sanitize content generated by AI agents to ensure safety and compliance."
    },
    {
      icon: Users,
      title: "Semantic Drift Detection",
      description: "Monitor and prevent AI agents from deviating from their intended purpose."
    },
    {
      icon: Network,
      title: "Real-time Monitoring",
      description: "Track and analyze AI agent behavior with comprehensive logging and analytics."
    },
    {
      icon: GitFork,
      title: "Policy Management",
      description: "Define and manage safety policies using simple YAML configuration files."
    },
    {
      icon: Code,
      title: "Framework Agnostic",
      description: "Works with any AI framework or LLM, providing consistent safety guardrails across your stack."
    }
  ]

  return (
    <div className="container py-24">
      <h2 className="text-3xl font-bold text-center mb-12">Key Features</h2>
      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
        {features.map((feature, index) => (
          <Card key={index} className="bg-card/50">
            <CardHeader>
              <div className="mb-4 w-12 h-12 rounded-full bg-primary/10 flex items-center justify-center">
                <feature.icon className="w-6 h-6 text-primary" />
              </div>
              <CardTitle>{feature.title}</CardTitle>
              <CardDescription>{feature.description}</CardDescription>
            </CardHeader>
          </Card>
        ))}
      </div>
    </div>
  )
} 